FROM node:22.22.3-slim AS dashboard

# GitHub source archives do not contain the UI generated by npm prepack.
# Build the same pinned AlphaClaw revision as the runtime dependency.
RUN apt-get update && apt-get install -y curl ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /build
RUN curl --fail --location https://github.com/chrysb/alphaclaw/archive/c3c9d023ba3c74a535a3cfb04e063f6c499554fa.tar.gz | tar -xz --strip-components=1
RUN npm ci --ignore-scripts && npm run build:ui

FROM node:22.22.3-slim

RUN apt-get update && apt-get install -y git curl procps python3 make g++ cron tini && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev --prefer-online && npm cache clean --force
COPY runtime ./runtime
RUN node ./runtime/patch-alphaclaw-webhook-dedupe.mjs
RUN node ./runtime/patch-alphaclaw-agents-entries.mjs
RUN node ./runtime/patch-section11-proxy.mjs
COPY --from=dashboard /build/lib/public/dist ./node_modules/@chrysb/alphaclaw/lib/public/dist
COPY --from=dashboard /build/lib/public/css/tailwind.generated.css ./node_modules/@chrysb/alphaclaw/lib/public/css/tailwind.generated.css
COPY --from=dashboard /build/lib/public/css/vendor ./node_modules/@chrysb/alphaclaw/lib/public/css/vendor
COPY managed-hooks ./managed-hooks
COPY managed-plugins ./managed-plugins

ENV PATH="/app/node_modules/.bin:$PATH"
ENV ALPHACLAW_ROOT_DIR=/data

RUN mkdir -p /data

EXPOSE 3000

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["sh", "-c", "if [ -f /data/.env ]; then sed -i '/^PATH=/d' /data/.env; fi; node /app/runtime/configure-openclaw.mjs && node /app/runtime/run-openclaw-doctor.mjs && node /app/runtime/configure-openclaw.mjs && node /app/runtime/configure-section11.mjs && exec alphaclaw start"]
